apiVersion: v1
kind: Pod
metadata:
  name: tools
  labels:
    name: tools
spec:
  containers:
  - name: tools
    image: ichte/coretools
    resources:
      limits:
        memory: "128Mi"      
        cpu: "100m"
    command:
      - "/bin/bash"
    args: ["-c", "while true; do echo 'busybox running'; sleep 10;done"]
