# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # make vm for testing
  config.vm.define "test" do |node|
    node.vm.box = "generic/centos7"
    node.vm.box_check_update = false
    # node.vbguest.auto_update = false
    node.vm.hostname = "test"
    node.vm.network "private_network", ip: "172.16.10.104"
    node.vm.provision "shell", path: "setup-vm.sh"   
  end

end
