apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  volumes:
    name: myvol
    persistenVolumeClaim: 
      claimName: pvc1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: busybox
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        command:
          - sleep
          - "600"
        volumeMounts:
          - name: myvol
            mountPath: "/data"

